add run_constrained on intel-openmp due to openmp issue
AnacondaRecipes/imbalanced-learn-feedstock pull request #4
Opened 2023-05-23 13:40 UTC by cbouss

Changes:
- not increasing the build number, as the pervious PR was not uploaded.
- add constraint on intel-openmp version osx-64

2023-05-23 14:59 UTC, skupr-anaconda approved these changes

2023-05-23 15:00 UTC, JeanChristopheMorinPerso requested changes

2023-05-23 15:00 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +    - intel-openmp <2023.1.0  # [osx and x86_64]
Can you add a comment to explain why this is done?

2023-05-23 15:06 UTC, cbouss commented on recipe/meta.yaml
> +    - intel-openmp <2023.1.0  # [osx and x86_64]
Now that I think of it, the issue is with scikit-learn. So I'd better add that restriction there..
I'll come back with new PRs.

2023-05-24 22:01 UTC, cbouss commented on recipe/meta.yaml
> +    - intel-openmp <2023.1.0  # [osx and x86_64]
In the end I added a comment.

2023-05-24 22:40 UTC, pseudoyim approved these changes
👍 Thank you!

2023-05-25 13:16 UTC, JeanChristopheMorinPerso approved these changes

2023-05-25 13:20 UTC, merged